services:
  db:
    image: postgres:latest
    volumes:
      - ./dockerConfig/postgres-dev-init.sql:/docker-entrypoint-initdb.d/init.sql
    environment:
      POSTGRES_USER: api
      POSTGRES_PASSWORD: secretPassword
      POSTGRES_DB: fast-way
    ports:
      - 5432:5432
